# Generated by Django 4.0.2 on 2022-02-21 12:05

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key_expire',
            field=models.DateTimeField(default=authapp.models.get_activation_key_expitarion_date),
        ),
    ]
