# Generated by Django 4.0.2 on 2022-02-21 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_user_activation_key_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expire',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 12, 39, 28, 125037, tzinfo=utc)),
        ),
    ]
