# Generated by Django 3.2.12 on 2022-02-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_userprofile_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
    ]
