# Generated by Django 4.0.1 on 2022-01-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstypes',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
