# Generated by Django 4.0.1 on 2022-01-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productstypes_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsTypes',
            new_name='ProductTypes',
        ),
    ]
