# Generated by Django 4.0.2 on 2022-02-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_alter_basket_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Товары в корзине'},
        ),
    ]
