# Generated by Django 4.0.2 on 2022-02-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_type',
            new_name='category',
        ),
    ]
